package org.botlibre.sdk.activity;


public enum EmotionalState {
	NONE,
	LOVE, LIKE, DISLIKE, HATE,
	RAGE, ANGER, CALM, SERENE,
	ECSTATIC, HAPPY, SAD, CRYING,
	PANIC, AFRAID, CONFIDENT, COURAGEOUS,
	SURPRISE, BORED,
	LAUGHTER, SERIOUS;	
}
